services:
  ros_env:
    build:
      context: .
      dockerfile: Containerfile
    container_name: ros2_workspace
    image: ghcr.io/florida-poly-ieee-ras-society/ros2-container-setup:latest
    network_mode: "host"
    ipc: "host"
    volumes:
      - ./ros_ws/src:/workspace/src:Z
    command: ["sleep", "infinity"]
